import { Router } from "express";
import crypto from "node:crypto";
import { z } from "zod";
import { Prisma } from "@prisma/client";
import { authenticate } from "../../middleware/authenticate.js";
import { authorize } from "../../middleware/authorize.js";
import { prisma } from "../../db/client.js";
import { recordPayment } from "./finance.service.js";

export const paymentsRouter=Router();

const createSchema=z.object({invoiceId:z.string().uuid(),provider:z.enum(["MANUAL","JAZZCASH","EASYPAISA","BANK","CARD","OTHER"]),amount:z.number().positive(),externalReference:z.string().max(200).optional(),checkoutUrl:z.string().url().max(2048).optional(),expiresAt:z.string().datetime({offset:true}).optional(),metadata:z.record(z.unknown()).optional()});
paymentsRouter.post("/intents",authenticate,authorize("finance:manage"),async(req,res)=>{const p=createSchema.safeParse(req.body);if(!p.success)return res.status(400).json({error:p.error.flatten()});const invoice=await prisma.feeInvoice.findUnique({where:{id:p.data.invoiceId},include:{payments:true,feeWaivers:true}});if(!invoice)return res.status(404).json({error:"Invoice not found"});const paid=invoice.payments.filter(x=>x.status!=="reversed").reduce((a,x)=>a.add(x.amount),new Prisma.Decimal(0));const waived=invoice.feeWaivers.reduce((a,x)=>a.add(x.amount),new Prisma.Decimal(0));const remaining=new Prisma.Decimal(invoice.amountDue).sub(waived).sub(paid);const amount=new Prisma.Decimal(p.data.amount);if(amount.gt(remaining))return res.status(400).json({error:"Payment intent exceeds the remaining invoice balance"});const intent=await prisma.paymentIntent.create({data:{invoiceId:p.data.invoiceId,provider:p.data.provider,amount,externalReference:p.data.externalReference,checkoutUrl:p.data.checkoutUrl,expiresAt:p.data.expiresAt?new Date(p.data.expiresAt):undefined,metadata:p.data.metadata as Prisma.InputJsonValue | undefined}});res.status(201).json({intent});});

function verifySignature(raw:Buffer,signature:string,secret:string){const expected=crypto.createHmac("sha256",secret).update(raw).digest("hex");const actual=Buffer.from(signature);const wanted=Buffer.from(expected);return actual.length===wanted.length&&crypto.timingSafeEqual(actual,wanted);}
const allowedWebhookProviders = new Set(["MANUAL","JAZZCASH","EASYPAISA","BANK","CARD","OTHER"]);\npaymentsRouter.post("/webhooks/:provider",async(req,res)=>{const provider=req.params.provider.toUpperCase();if(!allowedWebhookProviders.has(provider))return res.status(404).json({error:"Unsupported payment provider"});const secret=process.env["PAYMENT_WEBHOOK_SECRET_"+provider]||process.env.PAYMENT_WEBHOOK_SECRET;if(!secret)return res.status(503).json({error:"Payment webhook is not configured"});const signature=typeof req.headers["x-payment-signature"]==="string"?req.headers["x-payment-signature"]:"";const raw=(req as typeof req & { rawBody?: Buffer }).rawBody;if(!raw)return res.status(400).json({error:"Signed raw request body is required"});if(!signature||!verifySignature(raw,signature,secret))return res.status(401).json({error:"Invalid payment signature"});const p=z.object({intentId:z.string().uuid(),status:z.enum(["SUCCEEDED","FAILED","CANCELLED"]),externalReference:z.string().max(200).optional()}).safeParse(req.body);if(!p.success)return res.status(400).json({error:p.error.flatten()});try{const result=await prisma.$transaction(async tx=>{const intent=await tx.paymentIntent.findUnique({where:{id:p.data.intentId}});if(!intent||intent.provider!==provider)return null;if(intent.expiresAt&&intent.expiresAt.getTime()<Date.now()&&intent.status==="PENDING")return null;const claimed=await tx.paymentIntent.updateMany({where:{id:intent.id,status:"PENDING"},data:{status:p.data.status,externalReference:p.data.externalReference||intent.externalReference}});if(claimed.count===0){return tx.paymentIntent.findUnique({where:{id:intent.id}});}const updated=await tx.paymentIntent.findUnique({where:{id:intent.id}});if(!updated)throw new Error("Payment intent disappeared during webhook processing");if(p.data.status==="SUCCEEDED"){const existing=await tx.payment.findFirst({where:{invoiceId:intent.invoiceId,method:"ONLINE:"+provider,status:"posted",amount:intent.amount}});if(!existing){await tx.payment.create({data:{invoiceId:intent.invoiceId,amount:intent.amount,method:"ONLINE:"+provider,status:"posted"}});const inv=await tx.feeInvoice.findUnique({where:{id:intent.invoiceId},include:{payments:true,feeWaivers:true}});if(inv){const paid=inv.payments.filter(x=>x.status!=="reversed").reduce((a,x)=>a.add(x.amount),new Prisma.Decimal(0));const waived=inv.feeWaivers.reduce((a,x)=>a.add(x.amount),new Prisma.Decimal(0));await tx.feeInvoice.update({where:{id:inv.id},data:{status:paid.add(waived).gte(inv.amountDue)?"paid":"partial"}});}}}return updated;});if(!result)return res.status(404).json({error:"Payment intent not found"});res.json({intent:result});}catch(e){res.status(400).json({error:e instanceof Error?e.message:"Webhook processing failed"});}});
