import { Router } from "express";
import { z } from "zod";
import { Prisma } from "@prisma/client";
import { authenticate } from "../../middleware/authenticate.js";
import { authorize } from "../../middleware/authorize.js";
import { prisma } from "../../db/client.js";

export const operationsRouter = Router();
operationsRouter.use(authenticate);
const id=z.string().uuid();
const date=z.string().datetime({offset:true});

const leaveCreate=z.object({staffProfileId:id,leaveType:z.string().min(1).max(80),startDate:date,endDate:date,days:z.number().positive(),reason:z.string().max(2000).optional()});
operationsRouter.get("/hr/leaves",authorize("hr:view"),async(_req,res)=>res.json({leaves:await prisma.leaveRequest.findMany({include:{staff:{include:{user:true}},approvedBy:{select:{id:true,fullName:true}}},orderBy:{createdAt:"desc"}})}));
operationsRouter.post("/hr/leaves",authorize("hr:manage"),async(req,res)=>{const p=leaveCreate.safeParse(req.body);if(!p.success)return res.status(400).json({error:p.error.flatten()});if(new Date(p.data.endDate)<new Date(p.data.startDate))return res.status(400).json({error:"Leave end date cannot be before start date"});const overlap=await prisma.leaveRequest.findFirst({where:{staffProfileId:p.data.staffProfileId,status:{in:["PENDING","APPROVED"]},startDate:{lte:new Date(p.data.endDate)},endDate:{gte:new Date(p.data.startDate)}}});if(overlap)return res.status(409).json({error:"Leave request overlaps an existing pending or approved leave"});const leave=await prisma.leaveRequest.create({data:{...p.data,startDate:new Date(p.data.startDate),endDate:new Date(p.data.endDate),days:new Prisma.Decimal(p.data.days)}});res.status(201).json({leave});});
operationsRouter.post("/hr/leaves/:id/decision",authorize("hr:manage"),async(req,res)=>{if(!req.userId)return res.status(401).json({error:"Unauthenticated"});const p=z.object({status:z.enum(["APPROVED","REJECTED","CANCELLED"]),decisionNote:z.string().max(2000).optional()}).safeParse(req.body);if(!p.success)return res.status(400).json({error:p.error.flatten()});const leave=await prisma.leaveRequest.update({where:{id:req.params.id},data:{status:p.data.status,decisionNote:p.data.decisionNote,approvedByUserId:req.userId}});if(p.data.status==="APPROVED") await prisma.staffProfile.update({where:{id:leave.staffProfileId},data:{status:"ON_LEAVE"}}); else if(p.data.status==="REJECTED"||p.data.status==="CANCELLED") await prisma.staffProfile.update({where:{id:leave.staffProfileId},data:{status:"ACTIVE"}});await prisma.auditLog.create({data:{userId:req.userId,action:"hr:leave_decision",resource:"leave:"+leave.id,metadata:p.data}});res.json({leave});});

const period=z.object({label:z.string().min(1).max(100),startDate:date,endDate:date}).refine(x=>new Date(x.endDate)>new Date(x.startDate),{message:"End date must be after start date",path:["endDate"]});
operationsRouter.get("/payroll/periods",authorize("payroll:view"),async(_req,res)=>res.json({periods:await prisma.payrollPeriod.findMany({include:{records:{include:{staff:{include:{user:true}}}}},orderBy:{startDate:"desc"}})}));
operationsRouter.post("/payroll/periods",authorize("payroll:manage"),async(req,res)=>{const p=period.safeParse(req.body);if(!p.success)return res.status(400).json({error:p.error.flatten()});const x=await prisma.payrollPeriod.create({data:{label:p.data.label,startDate:new Date(p.data.startDate),endDate:new Date(p.data.endDate)}});res.status(201).json({period:x});});
const payrollRecord=z.object({payrollPeriodId:id,staffProfileId:id,basicSalary:z.number().nonnegative(),allowances:z.number().nonnegative().default(0),deductions:z.number().nonnegative().default(0),notes:z.string().max(2000).optional()});
operationsRouter.post("/payroll/records",authorize("payroll:manage"),async(req,res)=>{if(!req.userId)return res.status(401).json({error:"Unauthenticated"});const p=payrollRecord.safeParse(req.body);if(!p.success)return res.status(400).json({error:p.error.flatten()});const net=p.data.basicSalary+p.data.allowances-p.data.deductions;if(net<0)return res.status(400).json({error:"Deductions cannot exceed gross salary"});const periodState=await prisma.payrollPeriod.findUnique({where:{id:p.data.payrollPeriodId},select:{status:true}});if(!periodState)return res.status(404).json({error:"Payroll period not found"});if(periodState.status!=="DRAFT"&&periodState.status!=="APPROVED")return res.status(400).json({error:"Payroll period is not editable"});const r=await prisma.payrollRecord.create({data:{payrollPeriodId:p.data.payrollPeriodId,staffProfileId:p.data.staffProfileId,basicSalary:new Prisma.Decimal(p.data.basicSalary),allowances:new Prisma.Decimal(p.data.allowances),deductions:new Prisma.Decimal(p.data.deductions),netSalary:new Prisma.Decimal(net),notes:p.data.notes,createdByUserId:req.userId}});res.status(201).json({record:r});});
operationsRouter.post("/payroll/periods/:id/pay",authorize("payroll:manage"),async(req,res)=>{if(!req.userId)return res.status(401).json({error:"Unauthenticated"});const p=z.object({paymentReference:z.string().max(200).optional()}).safeParse(req.body);if(!p.success)return res.status(400).json({error:p.error.flatten()});try{const result=await prisma.$transaction(async tx=>{const period=await tx.payrollPeriod.findUnique({where:{id:req.params.id}});if(!period)throw new Error("Payroll period not found");if(period.status==="CLOSED"||period.status==="PAID")throw new Error("Payroll period is already closed or paid");const count=await tx.payrollRecord.count({where:{payrollPeriodId:period.id,status:{not:"VOID"}}});if(count===0)throw new Error("Cannot pay an empty payroll period");const now=new Date();await tx.payrollRecord.updateMany({where:{payrollPeriodId:period.id,status:{in:["DRAFT","APPROVED"]}},data:{status:"PAID",paidAt:now,paymentReference:p.data.paymentReference}});return tx.payrollPeriod.update({where:{id:period.id},data:{status:"PAID"}})});await prisma.auditLog.create({data:{userId:req.userId,action:"payroll:period_paid",resource:"payroll:"+req.params.id}});res.json({period:result});}catch(e){res.status(400).json({error:e instanceof Error?e.message:"Could not pay payroll"});}});

const lead=z.object({applicantName:z.string().min(2).max(200),guardianName:z.string().max(200).optional(),phone:z.string().max(40).optional(),email:z.string().email().optional(),desiredClass:z.string().max(100).optional(),source:z.string().max(80).optional(),notes:z.string().max(3000).optional()});
operationsRouter.get("/admissions/leads",authorize("admissions:view"),async(req,res)=>{const status=typeof req.query.status==="string"?req.query.status:undefined;res.json({leads:await prisma.admissionLead.findMany({where:status?{status}:undefined,include:{assignedTo:{select:{id:true,fullName:true}},convertedStudent:{include:{user:true}}},orderBy:{createdAt:"desc"}})}));
operationsRouter.post("/admissions/leads",authorize("admissions:manage"),async(req,res)=>{const p=lead.safeParse(req.body);if(!p.success)return res.status(400).json({error:p.error.flatten()});const x=await prisma.admissionLead.create({data:p.data});res.status(201).json({lead:x});});
operationsRouter.patch("/admissions/leads/:id",authorize("admissions:manage"),async(req,res)=>{const p=lead.partial().extend({status:z.enum(["NEW","CONTACTED","INTERVIEW","OFFERED","ENROLLED","REJECTED","LOST"]).optional(),assignedToUserId:id.optional()}).safeParse(req.body);if(!p.success)return res.status(400).json({error:p.error.flatten()});const x=await prisma.admissionLead.update({where:{id:req.params.id},data:p.data});res.json({lead:x});});

const vehicle=z.object({registrationNo:z.string().min(2).max(40),capacity:z.number().int().positive(),driverName:z.string().max(200).optional(),driverPhone:z.string().max(40).optional(),status:z.enum(["ACTIVE","MAINTENANCE","RETIRED"]).optional()});
operationsRouter.get("/transport/vehicles",authorize("transport:view"),async(_req,res)=>res.json({vehicles:await prisma.transportVehicle.findMany({include:{routes:true},orderBy:{registrationNo:"asc"}})}));
operationsRouter.post("/transport/vehicles",authorize("transport:manage"),async(req,res)=>{const p=vehicle.safeParse(req.body);if(!p.success)return res.status(400).json({error:p.error.flatten()});const x=await prisma.transportVehicle.create({data:p.data});res.status(201).json({vehicle:x});});
const routeSchema=z.object({name:z.string().min(2).max(120),pickupPoints:z.array(z.object({name:z.string().min(1),time:z.string().optional()})),monthlyFee:z.number().nonnegative().default(0),vehicleId:id.optional(),status:z.enum(["ACTIVE","INACTIVE"]).optional()});
operationsRouter.get("/transport/routes",authorize("transport:view"),async(_req,res)=>res.json({routes:await prisma.transportRoute.findMany({include:{vehicle:true,assignments:{include:{student:{include:{user:true}}}}},orderBy:{name:"asc"}})}));
operationsRouter.post("/transport/routes",authorize("transport:manage"),async(req,res)=>{const p=routeSchema.safeParse(req.body);if(!p.success)return res.status(400).json({error:p.error.flatten()});const x=await prisma.transportRoute.create({data:{name:p.data.name,pickupPoints:p.data.pickupPoints,monthlyFee:new Prisma.Decimal(p.data.monthlyFee),vehicleId:p.data.vehicleId,status:p.data.status}});res.status(201).json({route:x});});
const assignment=z.object({studentProfileId:id,routeId:id,pickupPoint:z.string().max(200).optional(),startDate:date,endDate:date.optional()});
operationsRouter.post("/transport/assignments",authorize("transport:manage"),async(req,res)=>{const p=assignment.safeParse(req.body);if(!p.success)return res.status(400).json({error:p.error.flatten()});const x=await prisma.transportAssignment.create({data:{studentProfileId:p.data.studentProfileId,routeId:p.data.routeId,pickupPoint:p.data.pickupPoint,startDate:new Date(p.data.startDate),endDate:p.data.endDate?new Date(p.data.endDate):undefined}});res.status(201).json({assignment:x});});

const item=z.object({sku:z.string().min(1).max(80),name:z.string().min(2).max(200),category:z.string().min(1).max(100),quantity:z.number().int().nonnegative().default(0),reorderLevel:z.number().int().nonnegative().default(0),unit:z.string().max(30).default("unit"),status:z.enum(["ACTIVE","DISCONTINUED"]).optional()});
operationsRouter.get("/inventory/items",authorize("inventory:view"),async(_req,res)=>res.json({items:await prisma.inventoryItem.findMany({include:{transactions:{orderBy:{createdAt:"desc"},take:10}},orderBy:{name:"asc"}})}));
operationsRouter.post("/inventory/items",authorize("inventory:manage"),async(req,res)=>{const p=item.safeParse(req.body);if(!p.success)return res.status(400).json({error:p.error.flatten()});const x=await prisma.inventoryItem.create({data:p.data});res.status(201).json({item:x});});
const stock=z.object({itemId:id,type:z.enum(["RECEIVE","ISSUE","ADJUST"]),quantity:z.number().int().positive(),unitCost:z.number().nonnegative().optional(),reference:z.string().max(200).optional(),notes:z.string().max(2000).optional()});
operationsRouter.post("/inventory/transactions",authorize("inventory:manage"),async(req,res)=>{if(!req.userId)return res.status(401).json({error:"Unauthenticated"});const p=stock.safeParse(req.body);if(!p.success)return res.status(400).json({error:p.error.flatten()});try{const x=await prisma.$transaction(async tx=>{const current=await tx.inventoryItem.findUnique({where:{id:p.data.itemId}});if(!current)throw new Error("Inventory item not found");const next=p.data.type==="RECEIVE"?current.quantity+p.data.quantity:p.data.type==="ISSUE"?current.quantity-p.data.quantity:p.data.quantity;if(next<0)throw new Error("Insufficient stock");await tx.inventoryItem.update({where:{id:current.id},data:{quantity:next}});return tx.inventoryTransaction.create({data:{itemId:current.id,type:p.data.type,quantity:p.data.quantity,unitCost:p.data.unitCost===undefined?undefined:new Prisma.Decimal(p.data.unitCost),reference:p.data.reference,notes:p.data.notes,createdByUserId:req.userId!}})});res.status(201).json({transaction:x});}catch(e){res.status(400).json({error:e instanceof Error?e.message:"Could not update inventory"});}});

const ptm=z.object({studentProfileId:id,parentUserId:id.optional(),teacherUserId:id.optional(),scheduledAt:date,durationMinutes:z.number().int().min(5).max(180).default(15),mode:z.enum(["IN_PERSON","ONLINE","PHONE"]).default("IN_PERSON"),agenda:z.string().max(2000).optional(),notes:z.string().max(4000).optional()});
operationsRouter.get("/ptm",authorize("ptm:view"),async(_req,res)=>res.json({meetings:await prisma.ptmMeeting.findMany({include:{student:{include:{user:true}},parent:{select:{id:true,fullName:true}},teacher:{select:{id:true,fullName:true}}},orderBy:{scheduledAt:"asc"}})}));
operationsRouter.post("/ptm",authorize("ptm:manage"),async(req,res)=>{if(!req.userId)return res.status(401).json({error:"Unauthenticated"});const p=ptm.safeParse(req.body);if(!p.success)return res.status(400).json({error:p.error.flatten()});const start=new Date(p.data.scheduledAt);const end=new Date(start.getTime()+p.data.durationMinutes*60000);const candidates=p.data.teacherUserId?await prisma.ptmMeeting.findMany({where:{status:"SCHEDULED",teacherUserId:p.data.teacherUserId,scheduledAt:{gte:new Date(start.getTime()-24*60*60*1000),lte:new Date(end.getTime()+24*60*60*1000)}}}):[]; const conflict=candidates.find(m=>{const existingEnd=new Date(m.scheduledAt.getTime()+m.durationMinutes*60000); return m.scheduledAt<end && existingEnd>start;}); if(conflict)return res.status(409).json({error:"Teacher has a conflicting PTM booking"});const x=await prisma.ptmMeeting.create({data:{...p.data,scheduledAt:start,createdByUserId:req.userId}});res.status(201).json({meeting:x});});
operationsRouter.patch("/ptm/:id",authorize("ptm:manage"),async(req,res)=>{const p=z.object({status:z.enum(["SCHEDULED","COMPLETED","CANCELLED","NO_SHOW"]).optional(),notes:z.string().max(4000).optional()}).safeParse(req.body);if(!p.success)return res.status(400).json({error:p.error.flatten()});res.json({meeting:await prisma.ptmMeeting.update({where:{id:req.params.id},data:p.data})});});
