import { Router } from "express";
import { z } from "zod";
import { Prisma } from "@prisma/client";
import argon2 from "argon2";
import crypto from "node:crypto";
import { authenticate } from "../../middleware/authenticate.js";
import { authorize } from "../../middleware/authorize.js";
import { prisma } from "../../db/client.js";

export const operationsRouter = Router();
operationsRouter.use(authenticate);
const id=z.string().uuid();
const date=z.string().datetime({offset:true});

const leaveCreate=z.object({staffProfileId:id,leaveType:z.string().trim().min(1).max(80),startDate:date,endDate:date,days:z.number().positive().max(366),reason:z.string().trim().max(2000).optional()});
operationsRouter.get("/hr/leaves",authorize("hr:view"),async(_req,res)=>res.json({leaves:await prisma.leaveRequest.findMany({include:{staff:{include:{user:true}},approvedBy:{select:{id:true,fullName:true}}},orderBy:{createdAt:"desc"}})}));
operationsRouter.post("/hr/leaves",authorize("hr:manage"),async(req,res)=>{const p=leaveCreate.safeParse(req.body);if(!p.success)return res.status(400).json({error:p.error.flatten()});const startDate=new Date(p.data.startDate);const endDate=new Date(p.data.endDate);if(endDate<startDate)return res.status(400).json({error:"Leave end date cannot be before start date"});const inclusiveDays=Math.floor((endDate.getTime()-startDate.getTime())/86400000)+1;if(p.data.days>inclusiveDays)return res.status(400).json({error:"Leave days cannot exceed the requested date range"});const staff=await prisma.staffProfile.findUnique({where:{id:p.data.staffProfileId},select:{id:true}});if(!staff)return res.status(404).json({error:"Staff profile not found"});try{const leave=await prisma.$transaction(async tx=>{await tx.$queryRaw`SELECT pg_advisory_xact_lock(hashtext(${p.data.staffProfileId}))`;const overlap=await tx.leaveRequest.findFirst({where:{staffProfileId:p.data.staffProfileId,status:{in:["PENDING","APPROVED"]},startDate:{lte:endDate},endDate:{gte:startDate}}});if(overlap)throw new Error("Leave request overlaps an existing pending or approved leave");return tx.leaveRequest.create({data:{staffProfileId:p.data.staffProfileId,leaveType:p.data.leaveType,startDate,endDate,days:new Prisma.Decimal(p.data.days),reason:p.data.reason}});});res.status(201).json({leave});}catch(e){res.status(409).json({error:e instanceof Error?e.message:"Could not create leave request"});}});
operationsRouter.post("/hr/leaves/:id/decision",authorize("hr:manage"),async(req,res)=>{if(!req.userId)return res.status(401).json({error:"Unauthenticated"});const p=z.object({status:z.enum(["APPROVED","REJECTED","CANCELLED"]),decisionNote:z.string().max(2000).optional()}).safeParse(req.body);if(!p.success)return res.status(400).json({error:p.error.flatten()});const leave=await prisma.$transaction(async tx=>{const existing=await tx.leaveRequest.findUnique({where:{id:req.params.id}});if(!existing)return null;if(existing.status!=="PENDING")throw new Error("Only pending leave requests can be decided");const claimed=await tx.leaveRequest.updateMany({where:{id:req.params.id,status:"PENDING"},data:{status:p.data.status,decisionNote:p.data.decisionNote,approvedByUserId:req.userId}});if(claimed.count!==1)throw new Error("Leave request was already decided");const updated=await tx.leaveRequest.findUnique({where:{id:req.params.id}});if(!updated)throw new Error("Leave request disappeared during decision");await tx.staffProfile.update({where:{id:updated.staffProfileId},data:{status:p.data.status==="APPROVED"?"ON_LEAVE":"ACTIVE"}});await tx.auditLog.create({data:{userId:req.userId!,action:"hr:leave_decision",resource:"leave:"+updated.id,metadata:p.data}});return updated;});if(!leave)return res.status(404).json({error:"Leave request not found"});res.json({leave});});

const period=z.object({label:z.string().min(1).max(100),startDate:date,endDate:date}).refine(x=>new Date(x.endDate)>new Date(x.startDate),{message:"End date must be after start date",path:["endDate"]});
operationsRouter.get("/payroll/periods",authorize("payroll:view"),async(_req,res)=>res.json({periods:await prisma.payrollPeriod.findMany({include:{records:{include:{staff:{include:{user:true}}}}},orderBy:{startDate:"desc"}})}));
operationsRouter.post("/payroll/periods",authorize("payroll:manage"),async(req,res)=>{const p=period.safeParse(req.body);if(!p.success)return res.status(400).json({error:p.error.flatten()});const startDate=new Date(p.data.startDate);const endDate=new Date(p.data.endDate);try{const x=await prisma.$transaction(async tx=>{await tx.$queryRaw`SELECT pg_advisory_xact_lock(hashtext('payroll-periods'))`;const overlap=await tx.payrollPeriod.findFirst({where:{startDate:{lte:endDate},endDate:{gte:startDate},status:{not:"CLOSED"}}});if(overlap)throw new Error("Payroll period overlaps an existing open period");return tx.payrollPeriod.create({data:{label:p.data.label,startDate,endDate}});});res.status(201).json({period:x});}catch(e){res.status(409).json({error:e instanceof Error?e.message:"Could not create payroll period"});}});
const payrollRecord=z.object({payrollPeriodId:id,staffProfileId:id,basicSalary:z.number().nonnegative(),allowances:z.number().nonnegative().default(0),deductions:z.number().nonnegative().default(0),notes:z.string().max(2000).optional()});
operationsRouter.post("/payroll/records",authorize("payroll:manage"),async(req,res)=>{if(!req.userId)return res.status(401).json({error:"Unauthenticated"});const p=payrollRecord.safeParse(req.body);if(!p.success)return res.status(400).json({error:p.error.flatten()});const basicSalary=new Prisma.Decimal(p.data.basicSalary);const allowances=new Prisma.Decimal(p.data.allowances);const deductions=new Prisma.Decimal(p.data.deductions);const net=basicSalary.add(allowances).sub(deductions);if(net.isNegative())return res.status(400).json({error:"Deductions cannot exceed gross salary"});try{const r=await prisma.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "payroll_periods" WHERE id = ${p.data.payrollPeriodId} FOR UPDATE`;const periodState=await tx.payrollPeriod.findUnique({where:{id:p.data.payrollPeriodId},select:{status:true}});if(!periodState)throw new Error("Payroll period not found");if(periodState.status!=="DRAFT")throw new Error("Payroll period is not editable");const staff=await tx.staffProfile.findUnique({where:{id:p.data.staffProfileId},select:{id:true}});if(!staff)throw new Error("Staff profile not found");const duplicate=await tx.payrollRecord.findFirst({where:{payrollPeriodId:p.data.payrollPeriodId,staffProfileId:p.data.staffProfileId,status:{not:"VOID"}}});if(duplicate)throw new Error("A payroll record already exists for this staff member in this period");return tx.payrollRecord.create({data:{payrollPeriodId:p.data.payrollPeriodId,staffProfileId:p.data.staffProfileId,basicSalary,allowances,deductions,netSalary:net,notes:p.data.notes,createdByUserId:req.userId!}});});res.status(201).json({record:r});}catch(e){res.status(409).json({error:e instanceof Error?e.message:"Could not create payroll record"});}});
operationsRouter.post("/payroll/periods/:id/approve",authorize("payroll:manage"),async(req,res)=>{if(!req.userId)return res.status(401).json({error:"Unauthenticated"});try{const result=await prisma.$transaction(async tx=>{const period=await tx.payrollPeriod.findUnique({where:{id:req.params.id}});if(!period)return null;if(period.status!=="DRAFT")throw new Error("Only draft payroll periods can be approved");const count=await tx.payrollRecord.count({where:{payrollPeriodId:period.id,status:{not:"VOID"}}});if(count===0)throw new Error("Cannot approve an empty payroll period");const updated=await tx.payrollPeriod.update({where:{id:period.id},data:{status:"APPROVED"}});await tx.auditLog.create({data:{userId:req.userId!,action:"payroll:period_approved",resource:"payroll:"+period.id}});return updated;});if(!result)return res.status(404).json({error:"Payroll period not found"});res.json({period:result});}catch(e){res.status(400).json({error:e instanceof Error?e.message:"Could not approve payroll"});}});
operationsRouter.post("/payroll/periods/:id/pay",authorize("payroll:manage"),async(req,res)=>{if(!req.userId)return res.status(401).json({error:"Unauthenticated"});const p=z.object({paymentReference:z.string().max(200).optional()}).safeParse(req.body);if(!p.success)return res.status(400).json({error:p.error.flatten()});try{const result=await prisma.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "payroll_periods" WHERE id = ${req.params.id} FOR UPDATE`;const period=await tx.payrollPeriod.findUnique({where:{id:req.params.id}});if(!period)throw new Error("Payroll period not found");if(period.status!=="APPROVED")throw new Error("Only an approved payroll period can be paid");const count=await tx.payrollRecord.count({where:{payrollPeriodId:period.id,status:{not:"VOID"}}});if(count===0)throw new Error("Cannot pay an empty payroll period");const now=new Date();await tx.payrollRecord.updateMany({where:{payrollPeriodId:period.id,status:{in:["DRAFT","APPROVED"]}},data:{status:"PAID",paidAt:now,paymentReference:p.data.paymentReference}});return tx.payrollPeriod.update({where:{id:period.id},data:{status:"PAID"}})});await prisma.auditLog.create({data:{userId:req.userId,action:"payroll:period_paid",resource:"payroll:"+req.params.id}});res.json({period:result});}catch(e){res.status(400).json({error:e instanceof Error?e.message:"Could not pay payroll"});}});

const lead=z.object({applicantName:z.string().min(2).max(200),guardianName:z.string().max(200).optional(),phone:z.string().max(40).optional(),email:z.string().email().optional(),desiredClass:z.string().max(100).optional(),source:z.string().max(80).optional(),notes:z.string().max(3000).optional()});
operationsRouter.get("/admissions/leads",authorize("admissions:view"),async(req,res)=>{const status=typeof req.query.status==="string"?req.query.status:undefined;res.json({leads:await prisma.admissionLead.findMany({where:status?{status}:undefined,include:{assignedTo:{select:{id:true,fullName:true}},convertedStudent:{include:{user:true}}},orderBy:{createdAt:"desc"}})});});
operationsRouter.post("/admissions/leads",authorize("admissions:manage"),async(req,res)=>{const p=lead.safeParse(req.body);if(!p.success)return res.status(400).json({error:p.error.flatten()});const x=await prisma.admissionLead.create({data:p.data});res.status(201).json({lead:x});});
operationsRouter.post("/admissions/leads/:id/convert",authorize("admissions:manage"),async(req,res)=>{if(!req.userId)return res.status(401).json({error:"Unauthenticated"});const p=z.object({email:z.string().email(),admissionNo:z.string().min(1).max(80),classId:id.optional(),sectionId:id.optional(),gender:z.enum(["Male","Female","Other"]).optional(),dateOfBirth:date.optional()}).safeParse(req.body);if(!p.success)return res.status(400).json({error:p.error.flatten()});try{const result=await prisma.$transaction(async tx=>{const lead=await tx.admissionLead.findUnique({where:{id:req.params.id}});if(!lead)throw new Error("Admission lead not found");if(lead.convertedStudentId)throw new Error("Admission lead is already converted");if(await tx.user.findUnique({where:{email:p.data.email}}))throw new Error("A user with this email already exists");if(p.data.classId&&p.data.sectionId){const section=await tx.section.findUnique({where:{id_classId:{id:p.data.sectionId,classId:p.data.classId}}});if(!section)throw new Error("Section does not belong to the selected class");}const temp=crypto.randomBytes(9).toString("base64url");const user=await tx.user.create({data:{email:p.data.email,passwordHash:await argon2.hash(temp),fullName:lead.applicantName,phone:lead.phone}});const student=await tx.studentProfile.create({data:{userId:user.id,admissionNo:p.data.admissionNo,classId:p.data.classId,sectionId:p.data.sectionId,gender:p.data.gender,dateOfBirth:p.data.dateOfBirth?new Date(p.data.dateOfBirth):undefined,admissionDate:new Date(),fatherName:lead.guardianName,guardianPhone:lead.phone,status:"ACTIVE"}});await tx.admissionLead.update({where:{id:lead.id},data:{status:"ENROLLED",convertedStudentId:student.id}});const role=await tx.role.findUnique({where:{key:"student"}});if(!role)throw new Error("Student role is not configured");await tx.userRole.create({data:{userId:user.id,roleId:role.id}});return {student,temp,email:user.email};});await prisma.auditLog.create({data:{userId:req.userId,action:"admissions:convert",resource:"admission:"+req.params.id,metadata:{studentId:result.student.id}}});res.status(201).json(result);}catch(e){res.status(400).json({error:e instanceof Error?e.message:"Could not convert admission"});}});
operationsRouter.patch("/admissions/leads/:id",authorize("admissions:manage"),async(req,res)=>{const p=lead.partial().extend({status:z.enum(["NEW","CONTACTED","INTERVIEW","OFFERED","ENROLLED","REJECTED","LOST"]).optional(),assignedToUserId:id.optional()}).safeParse(req.body);if(!p.success)return res.status(400).json({error:p.error.flatten()});const x=await prisma.admissionLead.update({where:{id:req.params.id},data:p.data});res.json({lead:x});});

const vehicle=z.object({registrationNo:z.string().min(2).max(40),capacity:z.number().int().positive(),driverName:z.string().max(200).optional(),driverPhone:z.string().max(40).optional(),status:z.enum(["ACTIVE","MAINTENANCE","RETIRED"]).optional()});
operationsRouter.get("/transport/vehicles",authorize("transport:view"),async(_req,res)=>res.json({vehicles:await prisma.transportVehicle.findMany({include:{routes:true},orderBy:{registrationNo:"asc"}})}));
operationsRouter.post("/transport/vehicles",authorize("transport:manage"),async(req,res)=>{const p=vehicle.safeParse(req.body);if(!p.success)return res.status(400).json({error:p.error.flatten()});const x=await prisma.transportVehicle.create({data:p.data});res.status(201).json({vehicle:x});});
const routeSchema=z.object({name:z.string().min(2).max(120),pickupPoints:z.array(z.object({name:z.string().min(1),time:z.string().optional()})),monthlyFee:z.number().nonnegative().default(0),vehicleId:id.optional(),status:z.enum(["ACTIVE","INACTIVE"]).optional()});
operationsRouter.get("/transport/routes",authorize("transport:view"),async(_req,res)=>res.json({routes:await prisma.transportRoute.findMany({include:{vehicle:true,assignments:{include:{student:{include:{user:true}}}}},orderBy:{name:"asc"}})}));
operationsRouter.post("/transport/routes",authorize("transport:manage"),async(req,res)=>{const p=routeSchema.safeParse(req.body);if(!p.success)return res.status(400).json({error:p.error.flatten()});const x=await prisma.transportRoute.create({data:{name:p.data.name,pickupPoints:p.data.pickupPoints,monthlyFee:new Prisma.Decimal(p.data.monthlyFee),vehicleId:p.data.vehicleId,status:p.data.status}});res.status(201).json({route:x});});
const assignment=z.object({studentProfileId:id,routeId:id,pickupPoint:z.string().max(200).optional(),startDate:date,endDate:date.optional()});
operationsRouter.post("/transport/assignments",authorize("transport:manage"),async(req,res)=>{const p=assignment.safeParse(req.body);if(!p.success)return res.status(400).json({error:p.error.flatten()});const startDate=new Date(p.data.startDate);const endDate=p.data.endDate?new Date(p.data.endDate):undefined;if(endDate&&endDate<startDate)return res.status(400).json({error:"Transport assignment end date cannot be before start date"});try{const result=await prisma.$transaction(async tx=>{const route=await tx.transportRoute.findUnique({where:{id:p.data.routeId},include:{vehicle:true}});if(!route||route.status!=="ACTIVE")throw new Error("An active transport route is required");if(route.vehicle){await tx.$queryRaw`SELECT id FROM "transport_vehicles" WHERE id = ${route.vehicle.id} FOR UPDATE`;const activeCount=await tx.transportAssignment.count({where:{routeId:route.id,status:"ACTIVE",startDate:{lte:endDate??new Date("9999-12-31T23:59:59.999Z")},OR:[{endDate:null},{endDate:{gte:startDate}}]}});if(activeCount>=route.vehicle.capacity)throw new Error("Transport vehicle capacity has been reached");}const student=await tx.studentProfile.findUnique({where:{id:p.data.studentProfileId},select:{id:true}});if(!student)throw new Error("Student profile not found");const overlap=await tx.transportAssignment.findFirst({where:{studentProfileId:p.data.studentProfileId,status:"ACTIVE",startDate:{lte:endDate??new Date("9999-12-31T23:59:59.999Z")},OR:[{endDate:null},{endDate:{gte:startDate}}]}});if(overlap)throw new Error("Student already has an overlapping transport assignment");return tx.transportAssignment.create({data:{studentProfileId:p.data.studentProfileId,routeId:p.data.routeId,pickupPoint:p.data.pickupPoint,startDate,endDate}});});res.status(201).json({assignment:result});}catch(e){res.status(409).json({error:e instanceof Error?e.message:"Could not create transport assignment"});}});

const item=z.object({sku:z.string().min(1).max(80),name:z.string().min(2).max(200),category:z.string().min(1).max(100),quantity:z.number().int().nonnegative().default(0),reorderLevel:z.number().int().nonnegative().default(0),unit:z.string().max(30).default("unit"),status:z.enum(["ACTIVE","DISCONTINUED"]).optional()});
operationsRouter.get("/inventory/items",authorize("inventory:view"),async(_req,res)=>res.json({items:await prisma.inventoryItem.findMany({include:{transactions:{orderBy:{createdAt:"desc"},take:10}},orderBy:{name:"asc"}})}));
operationsRouter.get("/inventory/low-stock",authorize("inventory:view"),async(_req,res)=>{const items=await prisma.inventoryItem.findMany({where:{status:"ACTIVE"}});res.json({items:items.filter(x=>x.quantity<=x.reorderLevel)});});
operationsRouter.post("/inventory/items",authorize("inventory:manage"),async(req,res)=>{const p=item.safeParse(req.body);if(!p.success)return res.status(400).json({error:p.error.flatten()});const x=await prisma.inventoryItem.create({data:p.data});res.status(201).json({item:x});});
const stock=z.object({itemId:id,type:z.enum(["RECEIVE","ISSUE","ADJUST"]),quantity:z.number().int().positive(),unitCost:z.number().nonnegative().optional(),reference:z.string().max(200).optional(),notes:z.string().max(2000).optional()});
operationsRouter.post("/inventory/transactions",authorize("inventory:manage"),async(req,res)=>{if(!req.userId)return res.status(401).json({error:"Unauthenticated"});const p=stock.safeParse(req.body);if(!p.success)return res.status(400).json({error:p.error.flatten()});try{const x=await prisma.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "inventory_items" WHERE id = ${p.data.itemId} FOR UPDATE`;const current=await tx.inventoryItem.findUnique({where:{id:p.data.itemId},select:{id:true,quantity:true,status:true}});if(!current)throw new Error("Inventory item not found");if(current.status!=="ACTIVE")throw new Error("Inventory item is not active");let next=current.quantity;if(p.data.type==="RECEIVE"){next=current.quantity+p.data.quantity;await tx.inventoryItem.update({where:{id:current.id},data:{quantity:next}});}else if(p.data.type==="ISSUE"){const changed=await tx.inventoryItem.updateMany({where:{id:current.id,status:"ACTIVE",quantity:{gte:p.data.quantity}},data:{quantity:{decrement:p.data.quantity}}});if(changed.count!==1)throw new Error("Insufficient stock or concurrent stock change");next=current.quantity-p.data.quantity;}else{next=p.data.quantity;await tx.inventoryItem.update({where:{id:current.id},data:{quantity:next}});}return tx.inventoryTransaction.create({data:{itemId:current.id,type:p.data.type,quantity:p.data.quantity,unitCost:p.data.unitCost===undefined?undefined:new Prisma.Decimal(p.data.unitCost),reference:p.data.reference,notes:p.data.notes,createdByUserId:req.userId!}})});res.status(201).json({transaction:x});}catch(e){res.status(400).json({error:e instanceof Error?e.message:"Could not update inventory"});}});

const asset=z.object({assetTag:z.string().min(1).max(100),assetType:z.string().min(1).max(100),condition:z.string().max(50).default("GOOD"),staffProfileId:id.optional(),studentProfileId:id.optional(),notes:z.string().max(2000).optional()}).refine(x=>Boolean(x.staffProfileId)||Boolean(x.studentProfileId),{message:"An asset must be assigned to a staff member or student"}).refine(x=>!(x.staffProfileId&&x.studentProfileId),{message:"Asset cannot be assigned to both staff and student"});
operationsRouter.get("/assets",authorize("asset:view"),async(_req,res)=>res.json({assets:await prisma.assetAssignment.findMany({include:{staff:{include:{user:true}},student:{include:{user:true}}},orderBy:{assignedAt:"desc"}})}));
operationsRouter.post("/assets",authorize("asset:manage"),async(req,res)=>{const p=asset.safeParse(req.body);if(!p.success)return res.status(400).json({error:p.error.flatten()});const x=await prisma.assetAssignment.create({data:p.data});res.status(201).json({asset:x});});
operationsRouter.post("/assets/:id/return",authorize("asset:manage"),async(req,res)=>{const existing=await prisma.assetAssignment.findUnique({where:{id:req.params.id}});if(!existing)return res.status(404).json({error:"Asset assignment not found"});if(existing.status==="RETURNED")return res.status(409).json({error:"Asset has already been returned"});const x=await prisma.assetAssignment.update({where:{id:req.params.id},data:{status:"RETURNED",returnedAt:new Date()}});res.json({asset:x});});

const ptm=z.object({studentProfileId:id,parentUserId:id.optional(),teacherUserId:id.optional(),scheduledAt:date,durationMinutes:z.number().int().min(5).max(180).default(15),mode:z.enum(["IN_PERSON","ONLINE","PHONE"]).default("IN_PERSON"),agenda:z.string().max(2000).optional(),notes:z.string().max(4000).optional()});
operationsRouter.get("/ptm",authorize("ptm:view"),async(_req,res)=>res.json({meetings:await prisma.ptmMeeting.findMany({include:{student:{include:{user:true}},parent:{select:{id:true,fullName:true}},teacher:{select:{id:true,fullName:true}}},orderBy:{scheduledAt:"asc"}})}));
operationsRouter.post("/ptm",authorize("ptm:manage"),async(req,res)=>{if(!req.userId)return res.status(401).json({error:"Unauthenticated"});const p=ptm.safeParse(req.body);if(!p.success)return res.status(400).json({error:p.error.flatten()});const start=new Date(p.data.scheduledAt);const end=new Date(start.getTime()+p.data.durationMinutes*60000);try{const x=await prisma.$transaction(async tx=>{if(p.data.teacherUserId){await tx.$queryRaw`SELECT pg_advisory_xact_lock(hashtext(${p.data.teacherUserId}))`;const candidates=await tx.ptmMeeting.findMany({where:{status:"SCHEDULED",teacherUserId:p.data.teacherUserId,scheduledAt:{gte:new Date(start.getTime()-24*60*60*1000),lte:new Date(end.getTime()+24*60*60*1000)}}});const conflict=candidates.find(m=>{const existingEnd=new Date(m.scheduledAt.getTime()+m.durationMinutes*60000);return m.scheduledAt<end&&existingEnd>start;});if(conflict)throw new Error("Teacher has a conflicting PTM booking");}return tx.ptmMeeting.create({data:{...p.data,scheduledAt:start,createdByUserId:req.userId!}});});res.status(201).json({meeting:x});}catch(e){res.status(409).json({error:e instanceof Error?e.message:"Could not create PTM meeting"});}});
operationsRouter.patch("/ptm/:id",authorize("ptm:manage"),async(req,res)=>{const p=z.object({status:z.enum(["SCHEDULED","COMPLETED","CANCELLED","NO_SHOW"]).optional(),notes:z.string().max(4000).optional()}).safeParse(req.body);if(!p.success)return res.status(400).json({error:p.error.flatten()});res.json({meeting:await prisma.ptmMeeting.update({where:{id:req.params.id},data:p.data})});});
